name: mobilediabeticapp
description: mobile diabetic app


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.13.0
  firebase: ^9.0.3
  git: ^2.2.1
  intl_phone_number_input: ^0.7.3+1
  twilio: ^0.0.2
  twilio_flutter: ^0.0.9
  protobuf: ^3.1.0
  email_otp: ^2.0.1
  sms_otp_auto_verify: ^2.1.0
  wave: ^0.2.2
  otp_text_field: ^1.1.3
  dropdown_textfield: ^1.0.8
  firebase_phone_auth_handler: ^1.0.8
  pinput: ^3.0.1
  multiselect_dropdown_flutter: ^0.0.7
  phone_auth_otp_ui: ^0.0.2
  telephony_sms: ^0.0.4
  hive: ^2.2.3
  url_launcher: ^6.2.2
  dart_dash_otp: ^1.3.3
  telephony: ^0.2.0
  mailer: ^6.1.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  #day_night_switcher: ^0.2.0+1
  #multiselect_formfield: ^0.1.7
  #python_ffi: ^0.4.4
  #flython: ^0.2.0
  #dcli: ^1.36.2
  #dartpy: ^0.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/Image 1.jpg
    - assets/Image 4.jpg
    - assets/Image 3.jpg
    - assets/Image 2.jpg
    - assets/default_profile_icon.png
    - assets/login.jpg
    - assets/login1.png
    - assets/signup.jpg


